import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/widgets/navbar';
import RootProvider from '@/providers/root.provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Better Auth Test',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="flex min-h-full flex-col">
        <RootProvider>
          <Navbar />
          <main className="flex flex-1 flex-col">{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
